[project]
name = "codepg"
version = "0.1.0"
description = "Automates File creation for Running Codes specific to programming languages. Useful tool for beginner programmers learning programming languages."
authors = [
    {name = "Akhilesh Malhti",email = "akhileshmalthi2299@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
codepg = "codepg.app:main"
